// Code generated by gobind. DO NOT EDIT.

// Java class frp.Frp is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/fatedier/frp/cmd/frp
package frp;

import go.Seq;

public abstract class Frp {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Frp() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxyFrpLogListener implements Seq.Proxy, FrpLogListener {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyFrpLogListener(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void log(String log);
	}
	
	
	public static native void runFrpc(String cfgDir, String cfgFile);
	public static native void runFrps(String cfgFile, boolean strictConfigMode);
	public static native void setFrpLogListener(FrpLogListener l);
	public static native void stopFrpc();
	public static native void stopFrps();
	public static native String version();
}
