// Code generated by gobind. DO NOT EDIT.

// Java class frpclib.Frpclib is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/fatedier/frp/cmd/frpc
package frpclib;

import go.Seq;

public abstract class Frpclib {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Frpclib() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native boolean close(String uid);
	public static native String getUids();
	public static native boolean isRunning(String uid);
	public static native String runContent(String uid, String cfgContent);
	public static native String runFile(String uid, String cfgFilePath);
}
