// Code generated by gobind. DO NOT EDIT.

// Java class frp.LogListener is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/fatedier/frp/cmd/frp
package frp;

import go.Seq;

public interface LogListener {
	public void log(String log);
	
}

